# railway.toml
project = "piwc-asokwa-bot"
directory = "backend"

[deploy]
# Start command to launch the FastAPI app
start = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[env]
GEMINI_API_KEY = AIzaSyBg_ri5fGQBzqgwH2mOt0PDfzui3co8oQM
